# Generated by Django 4.2.28 on 2026-02-18 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('clinic_hospital', models.CharField(blank=True, max_length=255)),
                ('appointment_type', models.CharField(choices=[('checkup', 'General Checkup'), ('specialist', 'Specialist Visit'), ('lab', 'Lab Test'), ('vaccination', 'Vaccination'), ('dental', 'Dental'), ('eye', 'Eye Checkup'), ('physiotherapy', 'Physiotherapy'), ('follow_up', 'Follow-up'), ('other', 'Other')], default='checkup', max_length=20)),
                ('date_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('send_whatsapp_reminder', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.family')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.familymember')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
