# Generated by Django 4.2.28 on 2026-02-18 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('blood_test', 'Blood Test'), ('urine_test', 'Urine Test'), ('xray', 'X-Ray'), ('mri', 'MRI'), ('ct_scan', 'CT Scan'), ('ecg', 'ECG'), ('echo', 'Echocardiogram'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('vaccination', 'Vaccination Card'), ('eye_test', 'Eye Test'), ('dental', 'Dental Report'), ('biopsy', 'Biopsy Report'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('report_date', models.DateField()),
                ('doctor', models.CharField(blank=True, max_length=255)),
                ('hospital_lab', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('is_abha_fetched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.family')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.familymember')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='VaultAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(default='view', max_length=20)),
                ('accessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.familymember')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.family')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='vault.report')),
            ],
        ),
    ]
