# Generated by Django 4.2.28 on 2026-02-18 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(help_text='e.g., 500mg, 1 tablet', max_length=100)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('thrice_daily', 'Three Times Daily'), ('four_times', 'Four Times Daily'), ('every_6h', 'Every 6 Hours'), ('every_8h', 'Every 8 Hours'), ('every_12h', 'Every 12 Hours'), ('weekly', 'Once a Week'), ('alternate', 'Alternate Days'), ('as_needed', 'As Needed (SOS)')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quantity_purchased', models.PositiveIntegerField(default=0, help_text='Total tablets/units purchased')),
                ('quantity_remaining', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=7, help_text='Alert when remaining < this value')),
                ('instructions', models.TextField(blank=True, help_text='With food, Before meal, etc.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medicine_photos/')),
                ('prescribed_by', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='accounts.familymember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicineRefillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('quantity_requested', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_requests', to='medicines.medicine')),
            ],
        ),
    ]
